### PR TITLE
вот

### PR DESCRIPTION
**Pull request by accuracy-itself**

### CODE REVIEW

**Comment by WildTiger404** [comment]
what's wrong with commit message and pull request message? Commit message should provide the information about what you've done on it. The pull request message should provide the information about what task you resolve. We are here to practice your work with git too, so if you don't know what to write on it you should use google to answer this question

**Comment by WildTiger404** [comment]
And I don't see your work. Please make sure you push the changes to your branch

**Comment by accuracy-itself** [comment]
> And I don't see your work. Please make sure you push the changes to your branch

Sorry, I'm not very goot at working with git but I'm trying to cope with it. And all the changes, I think, should be pushed to the branch now.

**Comment by WildTiger404** [comment]
nope. You commit your changes into main, So now this branch and the main branch contains your changes

**Pull request merged**
